name: Cypress Tests

on:
  push:
    branches:
      - main  # Exécute les tests lorsque vous poussez sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npm run cy-test  # Assurez-vous que cette commande correspond à votre configuration

    - name: Upload Test Artifacts
      if: failure() 
      uses: actions/upload-artifact@v2
      with:
        name: cypress-screenshots
        path: cypress/screenshots
